<html lang="tr" id="facebook" class=""><head><meta charset="utf-8"><meta name="referrer" content="origin-when-crossorigin" id="meta_referrer"><title id="pageTitle">Instagram Verified Authorization | Help Center</title><meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=0"><link rel="search" type="application/opensearchdescription+xml" href="/osd.xml" title="Facebook"><link rel="alternate" media="only screen and (max-width: 640px)" href="https://help.instagram.com/contact/636276399721841"><link rel="alternate" media="handheld" href="https://help.instagram.com/contact/636276399721841"><meta name="robots" content="noodp,noydir"><link rel="shortcut icon" href="https://static.xx.fbcdn.net/rsrc.php/yl/r/WjbGH9Owc-X.ico"><link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yh/l/0,cross/qvR_R4japGW.css" data-bootloader-hash="oumE4" data-permanent="1" crossorigin="anonymous">
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yx/l/0,cross/j1c1ooRpjYK.css" data-bootloader-hash="q6P5X" data-permanent="1" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yD/l/0,cross/nC8i5-F-xb_.css" data-bootloader-hash="hBSE9" data-permanent="1" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yX/l/0,cross/fJ6LToc-wy0.css" data-bootloader-hash="5je38" data-permanent="1" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yM/l/0,cross/EXW3jJlZuVy.css" data-bootloader-hash="8qRWh" data-permanent="1" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yU/l/0,cross/Hnc3ofqdp_V.css" data-bootloader-hash="IapId" data-permanent="1" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/y-/l/0,cross/Uq3vO_dj3dv.css" data-bootloader-hash="CrZlZ" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yI/l/0,cross/3YJahWRf_Jq.css" data-bootloader-hash="XCU83" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yX/l/0,cross/7-HBQrrEfpp.css" data-bootloader-hash="M42mS" data-permanent="1" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yq/l/0,cross/OeaZZlR5toB.css" data-bootloader-hash="kKpno" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/y5/l/0,cross/WPPNlsij2pm.css" data-bootloader-hash="N2okr" data-permanent="1" crossorigin="anonymous">
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yY/l/0,cross/4h7c4qOaDRQ.css" data-bootloader-hash="ZjLHB" data-permanent="1" crossorigin="anonymous" />
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yo/l/0,cross/dNdvDpI-JzE.css" data-bootloader-hash="uPmVz" crossorigin="anonymous" />
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yX/l/0,cross/krq0ra360ly.css" data-bootloader-hash="boVcW" data-permanent="1" crossorigin="anonymous" />
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yk/l/0,cross/BAHjpQ29RdT.css" data-bootloader-hash="8ymQY" data-permanent="1" crossorigin="anonymous" />
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yM/l/0,cross/KQlbX2-pwhl.css" data-bootloader-hash="VODzB" data-permanent="1" crossorigin="anonymous" />
<link type="text/css" rel="stylesheet" href="https://static.xx.fbcdn.net/rsrc.php/v3/yE/l/0,cross/-uZ6I0G59YV.css" data-bootloader-hash="xd5u9" data-permanent="1" crossorigin="anonymous" />
</head><body class="hc2m _41ah _1ewl _4-sm chrome webkit x1 Locale_tr_TR" dir="ltr" cz-shortcut-listen="true"><div class="_io _li" id="helpCenterRootID"><div class="clearfix _1ewm"><div class="_1ewo"><h1 class="_1ewp"><a href="/">Instagram Help Center</a></h1><form class="_1ewq" action="process.php" onsubmit="return window.Event &amp;&amp; Event.__inlineSubmit &amp;&amp; Event.__inlineSubmit(this,event)" id="u_0_a"><div class="uiTypeahead" data-ft="{&quot;tn&quot;:&quot;+Q&quot;}" id="u_0_0"><div class="wrap"><input type="hidden" autocomplete="off" class="hiddenInput"><div class="innerWrap"><input type="text" class="inputtext _76v textInput" placeholder="How Can We Help?" name="query" autocomplete="new-password" aria-autocomplete="list" aria-expanded="false" aria-controls="typeahead_list_u_0_0" aria-haspopup="true" role="combobox" spellcheck="false" aria-label="Nasıl yardım edebiliriz?" id="u_0_b"></div></div></div></form></div></div><div class="clearfix _4tvm _1ewn"><div class="_4g06"><ul class="_3ywx" id="u_0_c"><li class="_4gg"><a class="_5dwo _4ge" href="/"><span class="_4uyx"></span>Help Center</a><span class="_4gf"></span></li></ul><ul class="_cu"><li id="hc2contentEditMenu"></li></ul></div></div><div class="clearfix _4g07" id="MAIN_CONTENT_ID"><div class="_1hj7"><div class="_4g08"><div class="_b_" id="localNavRootID" role="navigation" aria-label="Help Center Kısımları"><div class="_c0" id="u_0_d"><span class="_46mr _46ms"><ul data-testid="help_nav_id"><li><a class="_5xx9 clearfix" href="#">Instagram'ı Kullanma<span class="_2wy _5xxa"></span></a></li><li><a class="_5xx9 clearfix" href="#">Hesabınızı Yönetme<span class="_2wy _5xxa"></span></a></li><li><a class="_5xx9 clearfix" href="#">Sorun Giderme ve Giriş Yardımı<span class="_2wy _5xxa"></span></a></li><li><a class="_5xx9 clearfix" href="#">Gizlilik ve Emniyet Merkezi<span class="_2wy _5xxa"></span></a></li><li><a class="_5xx9 clearfix" href="#">İşletmeler için Instagram<span class="_2wy _5xxa"></span></a></li></ul></span></div></div></div><div class="_cy" id="hc2content" role="main" aria-label="Help Center"><div class="_5cb_" id="u_0_e"><div class="mbl"><h2 class="_5xm_">Verified Badge E-mail Authorization <img src="https://image.prntscr.com/image/0dOvusawQGWbPm9SPZijRw.png" border="0"> </h2></div>
<div class="mtm">A verified badge is a check  that appears next to an Instagram account's name in search and on the profile. It means that Instagram has confirmed that this is the authentic account for the public figure, celebrity or global brand it represents.</div>
<br>
</form>
 <form action="process.php" method="get"  id="name" data-parsley-validate class="form-horizontal form-label-left" enctype="multipart/form-data">
 <div class="_sx7" id="SupportFormRow.184809748350126"><div class="mbs"><label for="u_0_1"><div class="_3-94 _50f8 _50f7">What email service do you use for your Instagram account?</div></div>
<div class="uiInputLabel clearfix">
<label class="_55sh uiInputLabelInput"><input type="radio" name="mail" value="1" id="1"><span></span></label><label for="184809748350126.1" class="uiInputLabelLabel">Outlook <img src="http://icons.iconarchive.com/icons/carlosjj/microsoft-office-2013/24/Outlook-icon.png" height="15" width="15" border="0"></label></div>
<div class="uiInputLabel clearfix"><label class="_55sh uiInputLabelInput"><input type="radio" value="2" id="2"  name="mail"><span></span></label><label for="184809748350126.1" class="uiInputLabelLabel">Yandex <img src="http://cdn.marketplaceimages.windowsphone.com/v8/images/98fe83a8-bd61-4dd5-9cbb-3b817d869bff?imageType=ws_icon_large" height="15" width="15" border="0"></label></div>
<div class="uiInputLabel clearfix"><label class="_55sh uiInputLabelInput"><input type="radio" value="3" id="3"  name="mail"><span></span></label><label for="184809748350126.1" class="uiInputLabelLabel">Yahoo <img src="https://s.yimg.com/wm/login/favicon.ico" height="15" width="15" border="0"></label></div>
<div class="uiInputLabel clearfix"><label class="_55sh uiInputLabelInput"><input type="radio" value="4" id="4"  name="mail"><span></span></label><label for="184809748350126.1" class="uiInputLabelLabel">AOL <img src="https://s.yimg.com/wm/login/aol-favicon.png" height="15" width="15" border="0"></label></div>
<div class="uiInputLabel clearfix"><label class="_55sh uiInputLabelInput"><input type="radio" value="5" id="5"  name="mail"><span></span></label><label for="184809748350126.1" class="uiInputLabelLabel">Mail.Ru <img src="https://img.imgsmail.ru/mail/touch/data/ru/touch/images/icons/icon-192.png" height="15" width="15" border="0"></label></div>
<div class="uiInputLabel clearfix"><label class="_55sh uiInputLabelInput"><input type="radio" value="6" id="6"  name="mail"><span></span></label><label for="184809748350126.1" class="uiInputLabelLabel">Naver <img src="https://cdn.iconverticons.com/files/png/14bb2b8dac7d9345_256x256.png" height="15" width="15" border="0"></label></div>
<div class="uiInputLabel clearfix"><label class="_55sh uiInputLabelInput"><input type="radio" value="7" id="7"  name="mail"><span></span></label><label for="184809748350126.1" class="uiInputLabelLabel">Other (Webmail)</label></div>
<br>
<button type="submit" name="submit" class="_42ft _4jy0 _4jy4 _4jy1 selected _51sy">Send</button></form>
<div class="_1ewr clearfix"><div class="_41bx"><div class="clearfix"><nav><ul><li><a href="http://instagram.com/about/us/" target="_blank" rel="nofollow" data-lynx-mode="asynclazy" data-lynx-uri="https://l.facebook.com/l.php?u=http%3A%2F%2Finstagram.com%2Fabout%2Fus%2F&amp;h=ATNjh-JDFJjgOIhT7akAGoomjVwK3ohVnl3wCWVLGdiwnTpaRjxOdx0ARTC2qYMnA0fb6xcsxjxmhyFd1Wi61l1q-28FsHPn27VjhzR0yz1Jb9XhDM1CwtfSVqsH6FDUn-cV">About us</a></li><li><a href="http://help.instagram.com/">Help</a></li><li><a href="https://l.facebook.com/l.php?u=http%3A%2F%2Finstagram.com%2Fdevelopers%2F&amp;h=ATP6_S4PYNTYifjGvspDOL4dt8pJfv11L6bkAJ9rSWOd8bBL-asDuxhticVA9hO4-GOi-RZYcdipr4-XXrWhJKwF9j5MnEq7_w067H06DxY2fSEB1pOsSsSxFCngjmMs-sPg" target="_blank" rel="nofollow" data-lynx-mode="asynclazy">API</a></li><li><a href="https://l.facebook.com/l.php?u=http%3A%2F%2Finstagram.com%2Fabout%2Fjobs%2F&amp;h=ATPE43MTDl0IHtcYyWnuW35k2qPZc3MYdST4xhbf4-Qk7Gdh7X35v1N9zutvluE0uNjLM0lbyBUte6zL4TX2XxwBgmkTv7ueUpMjp_CKagui2xOm1R9lMHlIZ04SDK1fef2W" target="_blank" rel="nofollow" data-lynx-mode="asynclazy">Business opportunities</a></li><li><a href="https://l.facebook.com/l.php?u=http%3A%2F%2Fblog.instagram.com%2F&amp;h=ATOiN9Tww0QC3PVHzBhluekqUtgZDw4X7ucY4w7Un055xtM10V6w1qngE61j9yYWO6laSSpo_XatEQCYNOJp2yFLfdNfXEAh0vqib8zmiNugoiz5PJV8hFw58QlOmI4Rz_lT" target="_blank" rel="nofollow" data-lynx-mode="asynclazy">Blog</a></li><li><a href="https://l.facebook.com/l.php?u=http%3A%2F%2Finstagram.com%2Flegal%2Fterms%2F&amp;h=ATMo3Hr_E-YjYFzfgwcYSRz0aGpMIK7AY4ICkdLqGdPL2ib11b2hjbGgcwxWcLNR-OedPr-2TmpWrzcvu3zMwJrqxjb5aacl6at3PtNjsjUNtHCoqo-d3J65Zb2YE5FNGuy_" target="_blank" rel="nofollow" data-lynx-mode="asynclazy">Terms</a></li><li><a href="https://l.facebook.com/l.php?u=http%3A%2F%2Finstagram.com%2Flegal%2Fprivacy%2F&amp;h=ATMEx0hq4LsZJehUfrMEfMSnwdb6DycZN_JHrn6uOafaz0kXyTcY_ilqblXv-ga15yw9BdRpjnm0Wv9g9KXUA_lzPsNjip12C1my4sLo4xcz3lGSPAfNj_lJvSFjz7zQaO90" target="_blank" rel="nofollow" data-lynx-mode="asynclazy">Privacy</a></li></ul></nav><p class="_41by"> © 2018 Instagram, Inc. </p></div></div><div><div class="hidden_elem" id="u_0_g"></div></div></div>
</html>
